version: "3.7"

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    working_dir: /frontend
    command: npm start
    ports:
      - "3000:3000"
  backend:
    build: ./backend
    container_name: backend-botics
    command: python3 main.py
    working_dir: /backend